# Generated by Django 5.1.5 on 2026-08-21 15:29

import apps.accounts.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text="Sert d'identifiant de connexion. Stockée en minuscules.", max_length=254, unique=True, verbose_name='adresse e-mail')),
                ('display_name', models.CharField(help_text='Nom affiché publiquement à côté des deals et commentaires.', max_length=40, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^[\\w.\\-]+$', 'Lettres, chiffres, point, tiret et souligné uniquement.')], verbose_name='pseudonyme')),
                ('role', models.CharField(choices=[('member', 'Membre'), ('moderator', 'Modérateur'), ('admin', 'Administrateur')], db_index=True, default='member', max_length=20, verbose_name='rôle')),
                ('preferred_language', models.CharField(choices=[('fr', 'Français'), ('nl', 'Nederlands'), ('de', 'Deutsch')], default='fr', max_length=5, verbose_name='langue préférée')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='accès au back-office')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='inscrit le')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text="Renseigné à la désinscription. La ligne n'est jamais supprimée.", null=True, verbose_name='désinscrit le')),
                ('anonymised_at', models.DateTimeField(blank=True, help_text='Renseigné une fois les données personnelles écrasées.', null=True, verbose_name='anonymisé le')),
                ('accepted_terms_at', models.DateTimeField(blank=True, null=True, verbose_name='CGU acceptées le')),
                ('marketing_consent', models.BooleanField(default=False, help_text='Consentement explicite, distinct des CGU (art. 7 RGPD).', verbose_name='consentement marketing')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('home_region', models.ForeignKey(blank=True, help_text='Sert à trier les deals de proximité. Facultatif.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='residents', to='catalog.region', verbose_name='région')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['role', 'is_active'], name='user_role_active_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('anonymised_at__isnull', True), ('deleted_at__isnull', False), _connector='OR'), name='user_anonymised_implies_deleted')],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
    ]
