# Generated by Django 5.1.5 on 2026-08-21 15:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('deals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actor_label', models.CharField(blank=True, help_text="Pseudonyme figé au moment de l'action, pour survivre à l'anonymisation.", max_length=80, verbose_name='auteur (copie)')),
                ('action', models.CharField(choices=[('user.registered', 'Inscription'), ('user.login', 'Connexion'), ('user.login_failed', 'Échec de connexion'), ('user.soft_deleted', 'Désinscription'), ('user.anonymised', 'Anonymisation'), ('user.data_exported', 'Export des données'), ('deal.submitted', 'Deal soumis'), ('deal.published', 'Deal publié'), ('deal.rejected', 'Deal refusé'), ('deal.updated', 'Deal modifié'), ('deal.deleted', 'Deal retiré'), ('comment.deleted', 'Commentaire supprimé'), ('payment.initiated', 'Paiement initié'), ('payment.succeeded', 'Paiement abouti'), ('payment.failed', 'Paiement échoué'), ('security.permission_denied', 'Accès refusé'), ('security.csrf_failure', 'Échec CSRF')], db_index=True, max_length=40, verbose_name='action')),
                ('target_id', models.CharField(blank=True, max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('path', models.CharField(blank=True, max_length=300)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='détails')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL, verbose_name="auteur de l'action")),
                ('target_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': "entrée d'audit",
                'verbose_name_plural': "journal d'audit",
                'ordering': ['-created_at'],
                'default_permissions': ('add', 'view'),
                'indexes': [models.Index(fields=['action', '-created_at'], name='audit_action_date_idx'), models.Index(fields=['actor', '-created_at'], name='audit_actor_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModerationDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('approved', 'Publiée'), ('rejected', 'Refusée'), ('expired', 'Marquée expirée')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='motif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_decisions', to='deals.deal')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moderation_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'décision de modération',
                'verbose_name_plural': 'décisions de modération',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('decision', 'rejected'), _negated=True), models.Q(('reason', ''), _negated=True), _connector='OR'), name='rejection_requires_reason')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('out_of_stock', 'Rupture de stock'), ('wrong_price', 'Prix incorrect'), ('misleading', 'Réduction trompeuse'), ('affiliate', "Lien d'affiliation personnel"), ('spam', 'Spam ou compte promotionnel')], max_length=30)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('resolved', 'Traité'), ('dismissed', 'Écarté')], db_index=True, default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='deals.deal')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports_filed', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'signalement',
                'verbose_name_plural': 'signalements',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('deal', 'reporter'), name='uniq_report_per_user_deal'), models.CheckConstraint(condition=models.Q(('status', 'open'), ('resolved_at__isnull', False), _connector='OR'), name='report_closed_requires_date')],
            },
        ),
    ]
