# Generated by Django 5.1.5 on 2026-08-21 15:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=30, unique=True, verbose_name='code')),
                ('name_fr', models.CharField(max_length=80)),
                ('name_nl', models.CharField(max_length=80)),
                ('name_de', models.CharField(max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='prix TVAC')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), help_text='Taux belge standard : 21 %.', max_digits=4, verbose_name='taux de TVA')),
                ('duration_days', models.PositiveSmallIntegerField(default=365, verbose_name='durée en jours')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'formule',
                'verbose_name_plural': 'formules',
                'ordering': ['price'],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='plan_price_non_negative'), models.CheckConstraint(condition=models.Q(('duration_days__gt', 0)), name='plan_duration_positive')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(help_text='Format DT-AAAA-NNNNNN, séquentiel et sans rupture.', max_length=30, unique=True, verbose_name='référence de facture')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='montant TVAC')),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='dont TVA')),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('succeeded', 'Réussi'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], db_index=True, default='pending', max_length=20)),
                ('gateway', models.CharField(default='sandbox', max_length=30, verbose_name='prestataire')),
                ('gateway_reference', models.CharField(help_text="Identifiant côté prestataire. Unique : garantit l'idempotence.", max_length=120, unique=True, verbose_name='référence prestataire')),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('card_brand', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='réglé le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='membre')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.plan')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expirée'), ('cancelled', 'Résiliée')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='payments.payment')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='payments.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'abonnement',
                'verbose_name_plural': 'abonnements',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', '-created_at'], name='payment_user_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payment_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('vat_amount__gte', 0), ('vat_amount__lte', models.F('amount'))), name='payment_vat_within_amount'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'succeeded'), _negated=True), ('settled_at__isnull', False), _connector='OR'), name='payment_succeeded_requires_settled_at'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('started_at'))), name='subscription_ends_after_start'),
        ),
    ]
