# Generated by Django 5.1.5 on 2026-08-21 15:29

import apps.accounts.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=140, validators=[django.core.validators.MinLengthValidator(15), apps.accounts.validators.validate_no_control_characters], verbose_name='titre')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name="identifiant d'URL")),
                ('description', models.TextField(max_length=4000, validators=[django.core.validators.MinLengthValidator(30), apps.accounts.validators.validate_no_control_characters], verbose_name='description')),
                ('external_url', models.URLField(max_length=600, verbose_name="lien vers l'offre")),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='prix')),
                ('reference_price', models.DecimalField(blank=True, decimal_places=2, help_text='Prix le plus bas pratiqué par le marchand durant les 30 jours précédents (Code de droit économique, art. VI.18).', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='prix de référence')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='devise')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='frais de livraison')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente de modération'), ('published', 'Publié'), ('rejected', 'Refusé'), ('expired', 'Expiré')], db_index=True, default='pending', max_length=20, verbose_name='statut')),
                ('is_cross_border', models.BooleanField(default=False, verbose_name='offre transfrontalière')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('nl', 'Nederlands'), ('de', 'Deutsch')], default='fr', max_length=5, verbose_name='langue de rédaction')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='début')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='fin')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='publié le')),
                ('temperature', models.IntegerField(db_index=True, default=100, help_text='Compteur dérivé de la table Vote, recalculable.', verbose_name='température')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='retiré le')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='catalog.category', verbose_name='catégorie')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='catalog.merchant', verbose_name='marchand')),
                ('regions', models.ManyToManyField(blank=True, related_name='deals', to='catalog.region', verbose_name='régions concernées')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_deals', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
            ],
            options={
                'verbose_name': 'deal',
                'verbose_name_plural': 'deals',
                'ordering': ['-temperature', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(2), apps.accounts.validators.validate_no_control_characters], verbose_name='commentaire')),
                ('is_verified_purchase', models.BooleanField(default=False, verbose_name='achat confirmé')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='supprimé le')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='deals.deal')),
            ],
            options={
                'verbose_name': 'commentaire',
                'verbose_name_plural': 'commentaires',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.SmallIntegerField(choices=[(-1, 'Refroidir'), (1, 'Réchauffer')], verbose_name='sens du vote')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='deals.deal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vote',
                'verbose_name_plural': 'votes',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='mot-clé')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='prix maximum')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'alerte',
                'verbose_name_plural': 'alertes',
                'constraints': [models.UniqueConstraint(fields=('user', 'keyword', 'category', 'region'), name='uniq_alert_per_user_criteria'), models.CheckConstraint(condition=models.Q(('max_price__isnull', True), ('max_price__gt', 0), _connector='OR'), name='alert_max_price_positive')],
            },
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['status', '-published_at'], name='deal_status_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['merchant', 'status'], name='deal_merchant_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='deal_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(('shipping_cost__gte', 0)), name='deal_shipping_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(('reference_price__isnull', True), ('reference_price__gt', models.F('price')), _connector='OR'), name='deal_reference_price_above_price'),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='deal_ends_after_start'),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'published'), _negated=True), ('published_at__isnull', False), _connector='OR'), name='deal_published_requires_date'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('deal', 'user'), name='uniq_vote_per_user_deal'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.CheckConstraint(condition=models.Q(('value__in', [-1, 1])), name='vote_value_is_minus_one_or_one'),
        ),
    ]
