# Generated by Django 5.1.5 on 2026-08-22 12:49

import apps.accounts.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealTranslation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('nl', 'Nederlands'), ('de', 'Deutsch')], max_length=5, verbose_name='langue')),
                ('title', models.CharField(max_length=140, validators=[django.core.validators.MinLengthValidator(15), apps.accounts.validators.validate_no_control_characters], verbose_name='titre')),
                ('description', models.TextField(max_length=4000, validators=[django.core.validators.MinLengthValidator(30), apps.accounts.validators.validate_no_control_characters], verbose_name='description')),
                ('is_machine_translated', models.BooleanField(default=False, help_text="À cocher tant qu'un humain n'a pas relu le texte.", verbose_name='traduction automatique')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='deals.deal')),
            ],
            options={
                'verbose_name': 'traduction de deal',
                'verbose_name_plural': 'traductions de deal',
                'ordering': ['language'],
                'constraints': [models.UniqueConstraint(fields=('deal', 'language'), name='uniq_deal_language')],
            },
        ),
    ]
