# Generated by Django 5.1.5 on 2026-08-21 15:29

import apps.accounts.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^BE[123]$', 'Codes admis : BE1, BE2, BE3.')], verbose_name='code NUTS-1')),
                ('name_fr', models.CharField(max_length=60, verbose_name='nom (fr)')),
                ('name_nl', models.CharField(max_length=60, verbose_name='nom (nl)')),
                ('name_de', models.CharField(max_length=60, verbose_name='nom (de)')),
            ],
            options={
                'verbose_name': 'région',
                'verbose_name_plural': 'régions',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name="identifiant d'URL")),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category', verbose_name='catégorie parente')),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'catégories',
                'ordering': ['position', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=5, verbose_name='langue')),
                ('name', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='libellé')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='catalog.category')),
            ],
            options={
                'verbose_name': 'libellé de catégorie',
                'verbose_name_plural': 'libellés de catégorie',
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, validators=[apps.accounts.validators.validate_no_control_characters], verbose_name='enseigne')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name="identifiant d'URL")),
                ('country', models.CharField(choices=[('BE', 'Belgique'), ('NL', 'Pays-Bas'), ('FR', 'France'), ('DE', 'Allemagne'), ('LU', 'Luxembourg')], db_index=True, default='BE', max_length=2, verbose_name='pays')),
                ('website', models.URLField(blank=True, max_length=300, verbose_name='site web')),
                ('vat_number', models.CharField(blank=True, help_text='Format belge uniquement, contrôlé par sa clé modulo 97.', max_length=20, validators=[apps.accounts.validators.validate_be_vat], verbose_name='numéro de TVA')),
                ('is_local_independent', models.BooleanField(default=False, help_text='Déclenche le badge « Commerçant local » dans le flux.', verbose_name='commerçant indépendant belge')),
                ('is_verified', models.BooleanField(default=False, help_text='Vérifiée par la modération : identité et site marchand contrôlés.', verbose_name='enseigne vérifiée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
            ],
            options={
                'verbose_name': 'marchand',
                'verbose_name_plural': 'marchands',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('is_local_independent', False), ('country', 'BE'), _connector='OR'), name='merchant_local_implies_be'), models.CheckConstraint(condition=models.Q(('vat_number', ''), ('country', 'BE'), _connector='OR'), name='merchant_vat_implies_be')],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='category_no_self_parent'),
        ),
        migrations.AddConstraint(
            model_name='categorytranslation',
            constraint=models.UniqueConstraint(fields=('category', 'language'), name='uniq_category_language'),
        ),
    ]
